import jsPDF from 'jspdf';

// Use relative URL so it works in production on Vercel
const API_URL = '/api';

export const saveReportToDB = async (type, patientId, data) => {
  try {
    const response = await fetch(`${API_URL}/reports`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ patientId, type, data }),
    });

    if (!response.ok) {
      let errorData;
      try {
        errorData = await response.json();
      } catch (e) {
        throw new Error('Failed to save report: Server error');
      }
      throw new Error(errorData.error || 'Failed to save report');
    }

    return await response.json();
  } catch (error) {
    console.error('Error saving report:', error);
    throw error;
  }
};

export const downloadPDF = async (reportType, patientId, reportData) => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  
  const pageWidth = pdf.internal.pageSize.getWidth();
  let y = 20;

  // Header
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(22);
  pdf.setTextColor(15, 30, 60);
  pdf.text('SANJEEVANI AI', pageWidth / 2, y, { align: 'center' });
  
  y += 8;
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  pdf.text('CLINICAL REPORT', pageWidth / 2, y, { align: 'center' });
  
  y += 15;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(20, y, pageWidth - 20, y);
  
  // Metadata
  y += 10;
  pdf.setFontSize(10);
  pdf.setTextColor(50, 50, 50);
  pdf.text(`Patient ID: ${patientId || 'N/A'}`, 20, y);
  pdf.text(`Date: ${new Date().toLocaleString()}`, pageWidth - 20, y, { align: 'right' });
  y += 6;
  pdf.text(`Report Type: ${reportType}`, 20, y);
  
  y += 10;
  pdf.line(20, y, pageWidth - 20, y);
  
  y += 15;

  const addSection = (title, content, isAlert = false) => {
    if (!content) return;
    if (y > 270) {
      pdf.addPage();
      y = 20;
    }
    
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(isAlert ? 220 : 30, isAlert ? 50 : 60, isAlert ? 50 : 120);
    pdf.text(String(title).toUpperCase(), 20, y);
    y += 6;
    
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(40, 40, 40);
    
    const splitText = pdf.splitTextToSize(String(content), pageWidth - 40);
    pdf.text(splitText, 20, y);
    
    y += (splitText.length * 5) + 10;
  };

  // Render content based on type
  if (reportType === 'VisionAI') {
    addSection('Image Type', reportData.imageType);
    addSection('Severity', reportData.severity, reportData.severity === 'Critical');
    addSection('Findings', reportData.findings);
    addSection('Impression', reportData.impression);
    addSection('AI Recommendation', reportData.recommendation, true);
  } else if (reportType === 'Genomic') {
    addSection('Detected Mutation', reportData.detectedMutation);
    addSection('Associated Disease', reportData.associatedDisease);
    addSection('Risk Level', reportData.riskLevel, reportData.riskLevel === 'High');
    addSection('Chromosome Location', reportData.chromosomeLocation);
    addSection('Clinical Significance', reportData.clinicalSignificance);
    addSection('Pathogenic Mechanism', reportData.description);
    if (reportData.crisprTarget) {
      addSection('CRISPR-Cas9 Target', reportData.crisprTarget);
    }
  } else if (reportType === 'ArtTherapy') {
    addSection('Psychological Insight', reportData.insight);
    addSection('Therapeutic Recommendation', reportData.recommendation);
    if (reportData.colorPalette) {
      addSection('Healing Palette', reportData.colorPalette.join(', '));
    }
  }

  // Footer
  pdf.setFont('helvetica', 'italic');
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text('This report was generated by Sanjeevani AI and should be reviewed by a certified healthcare professional.', pageWidth / 2, 285, { align: 'center' });

  pdf.save(`Sanjeevani_${reportType}_${patientId || 'Report'}.pdf`);
};
